apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: valueplus
  labels:
    role: api  # Change from incred-api to api to match deployment labels
spec:
  selector:
    role: api  # Change from incred-api to api to match deployment labels
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

